server:
  port: 9900
spring:
  application:
    name: api-gateway

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    myProduct:
      path: /myProduct/**
      serviceId: product
    product: /myProduct2/**
  ignored-patterns:
    - /**/product/listForOrder