spring:
  application:
    name: product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/imooc_spring_cloud_sell?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
  jpa:
    show-sql: true
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8
  rabbitmq:
    host: 192.168.106.128
    port: 5672
    username: guest
    password: guest
  zipkin:
    base-url: http://192.168.216.128:9411/
    sender:
      type: web
  sleuth:
    sampler:
#    抽样观察比例，默认值为0.1，百分比1，开发模式下发送所有的数据
      probability: 1
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


logging:
  level:
    org.springframework.cloud.openfeign: debug