spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/zhuqiang/imooc-spring-cloud-config-repo.git
          username: 99299684@qq.com
          password:
  rabbitmq:
    host: 192.168.106.128
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*" # bus-refresh


eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9050

